CREATE TABLE [room] (
  [Id] bigint PRIMARY KEY,
  [Name] nvarchar(100) NOT NULL,
  [CreatedAtUtc] datetime2(3) NOT NULL
)
GO

CREATE TABLE [monitor] (
  [Id] bigint PRIMARY KEY,
  [RoomId] bigint NOT NULL,
  [Name] nvarchar(100) NOT NULL,
  [FirmwareVersion] varchar(20),
  [LastHeartBeat] datetime2(3),
  [CreatedAtUtc] datetime2(3) NOT NULL
)
GO

CREATE TABLE [channel] (
  [Id] bigint PRIMARY KEY,
  [MonitorId] bigint NOT NULL,
  [PhysicalPort] tinyint NOT NULL,
  [CreatedAtUtc] datetime2(3) NOT NULL
)
GO

CREATE TABLE [channelAssignment] (
  [Id] bigint PRIMARY KEY,
  [ChannelId] bigint NOT NULL,
  [Label] nvarchar(100) NOT NULL,
  [StartDateUtc] datetime2 NOT NULL,
  [EndDateUtc] datetime2
)
GO

CREATE TABLE [telemetrySample] (
  [Id] bigint PRIMARY KEY,
  [ChannelId] bigint NOT NULL,
  [TimeStampUtc] datetime2(3) NOT NULL,
  [Voltage] decimal(8,3) NOT NULL,
  [Current] decimal(8,3) NOT NULL,
  [Power] decimal(10,3) NOT NULL,
  [CreatedAtUtc] datetime2(3)
)
GO

CREATE TABLE [telemetryMinute] (
  [ChannelId] bigint,
  [MinuteUtc] datetime2(0),
  [SampleCount] smallint NOT NULL,
  [MinPower] decimal(10,3) NOT NULL,
  [MaxPower] decimal(10,3) NOT NULL,
  [AvgPower] decimal(10,3) NOT NULL,
  [EnergyConsumedWh] decimal(12,4) NOT NULL,
  PRIMARY KEY ([ChannelId], [MinuteUtc])
)
GO

CREATE TABLE [telemetryHourly] (
  [ChannelId] bigint,
  [HourUtc] datetime2(0),
  [SampleCount] int NOT NULL,
  [MinPower] decimal(10,3) NOT NULL,
  [MaxPower] decimal(10,3) NOT NULL,
  [AvgPower] decimal(10,3) NOT NULL,
  [EnergyConsumedWh] decimal(12,4) NOT NULL,
  PRIMARY KEY ([ChannelId], [HourUtc])
)
GO

CREATE TABLE [telemetryDaily] (
  [ChannelId] bigint,
  [DateUtc] date,
  [SampleCount] int NOT NULL,
  [AvgPowerW] decimal(10,3) NOT NULL,
  [PeakPowerW] decimal(10,3) NOT NULL,
  [EnergyConsumedWh] decimal(12,4) NOT NULL,
  [EstimatedCost] decimal(12,4) NOT NULL,
  PRIMARY KEY ([ChannelId], [DateUtc])
)
GO

CREATE TABLE [energyTariff] (
  [Id] bigint PRIMARY KEY,
  [Name] nvarchar(100) NOT NULL,
  [CostPerKWh] decimal(10,4) NOT NULL,
  [EffectiveFromUtc] datetime2(3) NOT NULL,
  [EffectiveToUtc] datetime2(3)
)
GO

CREATE TABLE [aggregationCheckpoint] (
  [AggregationName] varchar(50) PRIMARY KEY,
  [LastProcessedUtc] datetime2(3) NOT NULL,
  [UpdatedAtUtc] datetime2(3) NOT NULL
)
GO

CREATE UNIQUE INDEX [channel_index_0] ON [channel] ("MonitorId", "PhysicalPort")
GO

CREATE INDEX [telemetrySample_index_1] ON [telemetrySample] ("ChannelId", "TimeStampUtc")
GO

EXEC sp_addextendedproperty
@name = N'Column_Description',
@value = 'Generated by firmware.',
@level0type = N'Schema', @level0name = 'dbo',
@level1type = N'Table',  @level1name = 'monitor',
@level2type = N'Column', @level2name = 'FirmwareVersion';
GO

EXEC sp_addextendedproperty
@name = N'Column_Description',
@value = 'RMS Electric Voltage',
@level0type = N'Schema', @level0name = 'dbo',
@level1type = N'Table',  @level1name = 'telemetrySample',
@level2type = N'Column', @level2name = 'Voltage';
GO

EXEC sp_addextendedproperty
@name = N'Column_Description',
@value = 'RMS Electric Current',
@level0type = N'Schema', @level0name = 'dbo',
@level1type = N'Table',  @level1name = 'telemetrySample',
@level2type = N'Column', @level2name = 'Current';
GO

EXEC sp_addextendedproperty
@name = N'Column_Description',
@value = 'Instantaneous Power (W)',
@level0type = N'Schema', @level0name = 'dbo',
@level1type = N'Table',  @level1name = 'telemetrySample',
@level2type = N'Column', @level2name = 'Power';
GO

EXEC sp_addextendedproperty
@name = N'Column_Description',
@value = 'Ingestion timestamp',
@level0type = N'Schema', @level0name = 'dbo',
@level1type = N'Table',  @level1name = 'telemetrySample',
@level2type = N'Column', @level2name = 'CreatedAtUtc';
GO

ALTER TABLE [monitor] ADD FOREIGN KEY ([RoomId]) REFERENCES [room] ([Id])
GO

ALTER TABLE [channel] ADD FOREIGN KEY ([MonitorId]) REFERENCES [monitor] ([Id])
GO

ALTER TABLE [channelAssignment] ADD FOREIGN KEY ([ChannelId]) REFERENCES [channel] ([Id])
GO

ALTER TABLE [telemetrySample] ADD FOREIGN KEY ([ChannelId]) REFERENCES [channel] ([Id])
GO

ALTER TABLE [telemetryMinute] ADD FOREIGN KEY ([ChannelId]) REFERENCES [channel] ([Id])
GO

ALTER TABLE [telemetryHourly] ADD FOREIGN KEY ([ChannelId]) REFERENCES [channel] ([Id])
GO

ALTER TABLE [telemetryDaily] ADD FOREIGN KEY ([ChannelId]) REFERENCES [channel] ([Id])
GO
